services:
  # 데이터베이스 서비스
  db:
    image: mysql:8.0 
    container_name: project2-db 
    restart: always 
    environment:
      MYSQL_DATABASE: restaurant_db 
      MYSQL_ROOT_PASSWORD: root_password 
    ports:
      - "3307:3306" 
    volumes:
      - ./mysql_data:/var/lib/mysql 

  # 백엔드 서비스
  backend:
    build: ./Project2_Spring 
    container_name: project2-backend 
    ports:
      - "8080:8080" 
    depends_on:
      - db 
    environment:
      # 주소값을 'localhost'가 아닌 docker-compose 서비스 이름인 'db'로 적어야 통신이 됩니다.
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/restaurant_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password

  # 프론트엔드 서비스 추가
  frontend:
    build: ./Project2_Front
    container_name: project2-frontend
    ports:
      - "5173:80" # 호스트의 5173 포트로 접속 시 컨테이너 Nginx(80)로 연결
    depends_on:
      - backend
    restart: always